jobs:
- job: Build
  pool:
    name: Hosted Ubuntu 1604   
  variables:
    solution: 'NerdAllDebug.Sample.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    packageMessageNerdAllDebug: 'NerdAllDebug.Sample.App.Messages'
    packageClientNerdAllDebug: 'NerdAllDebug.Sample.Host.Client'
  workspace:
    clean: resources
  steps:
  - task: NuGetCommand@2
    displayName: 'Authenticate with Azure DevOps NuGet SotreqLink Packages'
    inputs:
      command: custom
      arguments: sources update -Name "SotreqLink-Packages" -Username "vsts" -Password "$(System.AccessToken)" -StorePasswordInClearText -ConfigFile ./NuGet.config
    timeoutInMinutes: 60
  - script: | 
      dotnet build $(System.DefaultWorkingDirectory)/$(solution) --configuration $(buildConfiguration) 
      dotnet test $(System.DefaultWorkingDirectory)/$(solution) --configuration $(buildConfiguration) --logger trx --collect:"Code Coverage" --no-build
    displayName: 'Build dotnet $(buildConfiguration)'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
    displayName: 'Publish Test Results'
  - task: CopyFiles@2
    displayName: 'Copy package $(packageMessageNerdAllDebug)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/$(packageMessageNerdAllDebug)/bin/$(buildConfiguration)/'
      Contents: '*.nupkg'
      TargetFolder: '$(build.artifactstagingdirectory)/$(packageMessageNerdAllDebug)/bin/$(buildConfiguration)'
      CleanTargetFolder: true
      OverWrite: true
    timeoutInMinutes: 60
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/$(packageMessageNerdAllDebug)/bin/$(buildConfiguration)'
      ArtifactName: '$(packageMessageNerdAllDebug)-package'      
    displayName: 'Publishing package $(packageMessageNerdAllDebug)'
    timeoutInMinutes: 60
  - task: CopyFiles@2
    displayName: 'Copy package $(packageClientNerdAllDebug)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/$(packageClientNerdAllDebug)/bin/$(buildConfiguration)/'
      Contents: '*.nupkg'
      TargetFolder: '$(build.artifactstagingdirectory)/$(packageClientNerdAllDebug)/bin/$(buildConfiguration)'
      CleanTargetFolder: true
      OverWrite: true
    timeoutInMinutes: 60
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/$(packageClientNerdAllDebug)/bin/$(buildConfiguration)'
      ArtifactName: '$(packageClientNerdAllDebug)-package'      
    displayName: 'Publishing package $(packageClientNerdAllDebug)'
    timeoutInMinutes: 60
- job: DocFX
  pool:
    vmImage: 'ubuntu-16.04'
  container: diogenesalves/docfx-run:latest
  variables:
    docFXFolderMessageNerdAllDebug: 'NerdAllDebug.Sample.App.Messages'
    docFXFolderClientNerdAllDebug: 'NerdAllDebug.Sample.Host.Client'
  steps:
  - script: |
      \cp /docfx/docfx.json $(Build.SourcesDirectory)/$(docFXFolderMessageNerdAllDebug)/
      mono /docfx/docfx.exe $(Build.SourcesDirectory)/$(docFXFolderMessageNerdAllDebug)/docfx.json
    displayName: 'Executing DocFX $(docFXFolderMessageNerdAllDebug)'
    timeoutInMinutes: 60
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/$(docFXFolderMessageNerdAllDebug)/_site/api'
      ArtifactName: '$(docFXFolderMessageNerdAllDebug)'
      ArtifactType: container
      TargetPath: ''
    displayName: 'Publishing DocFX $(docFXFolderMessageNerdAllDebug)'
    timeoutInMinutes: 60
  - script: |
      \cp /docfx/docfx.json $(Build.SourcesDirectory)/$(docFXFolderClientNerdAllDebug)/
      mono /docfx/docfx.exe $(Build.SourcesDirectory)/$(docFXFolderClientNerdAllDebug)/docfx.json
    displayName: 'Executing DocFX $(docFXFolderClientNerdAllDebug)'
    timeoutInMinutes: 60
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/$(docFXFolderClientNerdAllDebug)/_site/api'
      ArtifactName: '$(docFXFolderClientNerdAllDebug)'
      ArtifactType: container
      TargetPath: ''
    displayName: 'Publishing DocFX $(docFXFolderClientNerdAllDebug)'
    timeoutInMinutes: 60